### ISSUE TITLE
Metadata Editing

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#222]
1) I can edit the yellow text (title?) but not the white text (name). What if I want to change the white text too? 

2) Not clear on a dataset page the distinction between the yellow text and white text.  Perhaps on hover explain the yellow text is what i'll be using in SQL

3) From Structure view, hoping to have ability to edit /add context to the columns - to explain what the column content is

4) When you click into "Commits" on a Dataset, "Details" section doesn't seem to update or copy description over from the main page.

**Comment by ramfox** [comment]
1. you can change both, but it is definitely confusing and should be changed. As it stands now, clicking 'rename' will change the yellow text (which is the name), and you can change the white text (the title) through the metadata edit page.

2. Yes needs a better explanation...

3. Yes, def

4. Not totally sure what the bug is here, would you mind explaining further? @rgardaphe

**Comment by ramfox** [comment]
Closing due to age and because I believe the but in 4) has been fixed.
