### ISSUE TITLE
Refactor state tree, reducers, and selectors

### ISSUE THREAD

**Issue by ramfox** [qri-io/2017-frontend#255]
Now that we have peerIDs, there is no reason for our state tree to be so fractured :)

Let's refactor the state tree (and associated reducers and selectors) to be more streamlined.

## State tree changes:
* All datasets (even those belonging to peers) should exists in `state.entities.datasets`
* Remove `state.entities.peernamespace`
* Add `state.entities.peers` that stores profiles whose keys are the peerid
* Edit `state.session` to keep track of the userID (if it has one) (`state.session.id`)

## Pagination Reducer changes:
* `state.pagination.peers`  ids is a list of peer ids
* `state.pagination.datasets`, key is peerID, each peerID has its own pagination *** INCLUDES OUR OWN PEERID AND DATASETS***
eg:
```
state.pagination.datasets ={
  somePeerID: {
      ids: [
          QmXb...,
          Qmyz...      
     ],
    all the other pagination stuff...,
  }
}
```

## Selector changes
* Will update with selector changes.

### Major idea here is that everything is accessed with either the peerID or the hash, we don't use the mutable names as the way to get to a dataset or a peer!!!

The current plan for how to tackle (might not be the best plan way, but going to try it):
* change state tree one part at a time, starting with session
* add necessary schemas
* change necessary actions
* add reducers
* add reducer tests
* add selectors
* add selector tests

rinse and repeat, probably in this order:
* [x] session
* [x] peer ids list (changed when you call LoadPeers, or LoadPeer), call stores the profile in state.entities.peer, adds ids to paginated list 
	(if LoadPeer is called, we see if peerid already exists first before fetching, if it doesn't exists add peer id to top of list)
* [x] nuke peerdatasets, and change actions that loadPeerdatasets to add to full datasets list, add entry into pagination: state.entities.datasets

**Comment by ramfox** [comment]
hey @b5 I have some questions about ‘session’ and its function

I think it's hold over from previous versions of the app, but I'm not sure how it relates to what we have going on now. I know how I shoe-horned it to work the way I want, but I'm wondering if we need it anymore.

Right now, session is related to profile, fetchSessionUser fetches the profile. The profile is added to state.entities.session and changes a field in the state.session.requestedSession from false to true.

No where else in the app is requestedSession checked.

It doesn't feel like session and profile are exact matches as a concept, since in our read-only version, we can have a session without having an associated profile.

It feels like state.session should be nixed for now, to be replaced by state.profile. The profile data should end up in `state.entities.peers` (where all the peer profiles live), and the peerid that comes back from the profile_request should live in `state.id`. This follows the concept outlined above, where all the information lives together, and we pick out what we need using the peerid or hash

LoadProfile should happen in the App component, only if READ_ONLY is false. 

Need to think through the rest of this, (what happens if LoadProfile comes back with an empty id, a failure, etc. Basically, how do we deal with not having an id. In read-only mode this is fine and in fact the normal state of the world, but when we are in user-mode, and the id is wrong or messed up, our basic truth about the world is wrong. What to display and how to handle?)

**Comment by b5** [comment]
`state.session` is meant to represent the currently "logged in" user. This is indeed a carry over from previous iterations of the frontend, but the concept of a session has newfound relevance in relation to our new "read only" mode.

Traditional webapps model the concept of a session to reflect the current user, and the app adjusts based on present / lack of a session. For example, I just tried to "clap" a post on medium without being logged-in (aka having no session), and it showed me a message saying I need to sign up first.

This is the exact behavior we're after in the frontend. instead of checking for a READ_ONLY flag, we should be checking weather an API call to `/me` (or some equivelent) returns a 200 status & profile in it's response. 

Components can achieve this by accepting an _optional_ `session` property that is either noting, or a peer profile object. If it's a peer profile they can do cool stuff like show the peer's avatar, peername, etc. But the state of _not_ having a profile shouldn't be an errror, it should just affect what the component presents.

The whole process of making the frontend "read only" can be boiled down to setting the session object to `undefined`, seeing what breaks, and adjusting accordingly.

So, I think we should _keep_  the concept of session, but use the exact approach you described. Store the profile data in peers, and just keep `state.session : peerID`. We can use a special selector `selectSessionPeer` that checks this spot in state for the session peer, and if it's not there, we should show "read only stuff"

**Comment by ramfox** [comment]
Okay, this is cool. I’m excited about making these changes. After thinking about it a bit, it feels like what need to do is still focus on the state, reducers, and selectors, get those down pat, and then rewire the containers and components with session in mind.

**Comment by b5** [comment]
completely. [Start from the bottom](https://giphy.com/gifs/car-snow-drake-Wscf4kPB88TnO)
