### ISSUE TITLE
Where to put the peer/user hash.

### ISSUE THREAD

**Issue by rgardaphe** [qri-io/2017-frontend#320]
Consider moving the hash into the user profile (Right hand size of the user profile page) rather than adjacent to the picture. 

**Example:**
Name: Jane Simpson
Hash: Qd2ifj04jg8384uh23r13nf823na
Twitter: @twitterjane

Small concern that the hash will be odd/new concept for new users, kinda looks like loose jibberish text like "lorem ipsum"

**Alternatives:**
  - another chance for tooltips to help
  - could we just hide this?
  - better label?

**Comment by ramfox** [comment]
I'm of so many minds about this.

My gut reaction to moving to the bio was so positive, but then I wondered if that would generate even more confusion, since it would be in contrast to details that are so clear and well known.

When it's under the profile name it makes it feel more tied to identity.

Maybe just calling it `qri id` or `id` rather than `hash` would just make it less confusion in general.

_Do we even need the id on the frontend? _
I'm having a hard time letting go of having the id on the frontend. It just feels like important info that a user wont need on a daily basis, but might need if something goes wrong.

**Comment by ramfox** [comment]
this last round of mockups removed the qri peerid from the frontend.
