### ISSUE TITLE
editing metadata: citations text field error caused when only one item is added

### ISSUE THREAD

**Issue by osterbit** [qri-io/2017-frontend#342]
screenshot: 
![image](https://user-images.githubusercontent.com/3967296/40390327-d9df5c7e-5de2-11e8-9ae4-39d858fa33fc.png)

could either change the form from a text field to something more restrictive or add a special case for a single item to be interpreted as a slice of length 1

**Comment by ramfox** [comment]
Yea, so this is actually because citations are structured as strings on this webapp, but unmarshal to type dataset.Citations. Dataset.Citations are actually a struct:
type Citation struct {
	Name  string `json:"name,omitempty"`
	URL   string `json:"url,omitempty"`
	Email string `json:"email,omitempty"`
}

So on the front end we need to create custom components for Citation and Contributors that organize this info correctly when we send the updated metadata back to qri.
