### ISSUE TITLE
All dataset components in the editor must be nil by default and removable

### ISSUE THREAD

**Issue by b5** [qri-io/2017-frontend#418]
This started off with the realization that because the frontend supplies a default schema, csv schema inference is broken. Because we can't remove/provide empty structure on frontend, there's no way to get the backend to do it's inference tricks.
 
The best way to fix this is to take the approach we use for `transform` and `viz` sections and apply it to _all_ dataset components. Now that we've gone through a bunch of work on refactoring the save path on the backend, this should be totally fine. As a concrete example, going to the editor and hitting `Reset` should remove all components, so clicking the `body` tab in the editor should initially show an `Add Body` button. Clicking `Add Body` should create the body component, make the editor visible, and place a "remove body" button on-screen.

While we're here, we should scrub through dataset editing actions to make sure removal actually removes the components. This should address #407. We _might_ need to do some work on the API to make sure nil components properly are properly parsed.

**Comment by ramfox** [comment]
kk, this is a bit odd. Let me layout what I've found.

Out basic issue is that having any structure present means that we never detect the schema. Overall, we need to make an adjustment to the backend in `Base.InferValues` that will still infer a schema if no schema is present. Right now, it only check to see if we have a structure, and if any structure is present it will not infer a schema

1) structure.format effects the frontend => if it's json or csv we display the body differently in the editor. We can remove this, and instead have the json/csv toggle happen on the body page, and use that to determine what format is shown on the structure page (if we have a structure)

2) We need either the structure or a file extension in order to open/create the files on the backend. Right now on the frontend, we are not adding file extensions to the files we send to the api. If we do this, then we are in an okay spot, as long as the user has not added their own structure. I will say the code path on the backend for this is a bit rando.

**Comment by ramfox** [comment]
More notes:

We need structure, because we need `structure.format` to be filled in if we are trying to send a file. 

We circumvent this, initially, by adding an extension when we prepare the file. This (at the api level, will detect & create a structure based on the file format)

We send lib.Save a datasetPod with the BodyPath = 'body' and BodyBytes

In Actions we call base.DatasetPodBodyFile, we create an in mem cafs file. If we don't have 'format' filled out in structure, we error.

Then in Base.InferValues, we only attempt to create a structure is there is no structure. We should probably also see if there is a schema instead. If no schema, then we detect as well!
